language: scala

jdk:
  - oraclejdk8

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2

env:
  matrix:
    - SCALAJS_VERSION=1.0.0-M2
    - SCALAJS_VERSION=0.6.21

install:
  - nvm list
  - nvm install 5.10.0
  - nvm use 5.10.0

before_script:
  # Init xvfb for headless browser testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Start test server
  - cd test/server && npm install && node index.js &

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - test/update-readme-sanity-check.sh --fatalDiff
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJS/test
  - sbt ++$TRAVIS_SCALA_VERSION scalaHttpJVM/test
  # - sbt ++$TRAVIS_SCALA_VERSION firefox:test
